version: "3.9"
services:
  db:
    container_name: app_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432